- uses: Platane/snk/svg-only@v3
  with:
    # github user name to read the contribution graph from
    github_user_name: ${{ github.repository_owner }}

    # list of files to generate
    outputs: |
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark
      "dist/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"
      "dist/ocean-dark.svg?palette=github-dark&color_snake=orange&color_dots=#0d1117,#161b22,#1f2937,#2563eb,#3b82f6"
